export {default as member1 } from "./member-1.jpeg";
export {default as member2 } from "./member-2.jpeg";
export {default as member3 } from "./member-3.jpeg";
export {default as member4 } from "./member-4.jpeg";

export {default as profile3} from "./profile-3.jpeg";
export {default as profile4} from "./profile-4.jpeg";
export {default as profile5} from "./profile-5.jpg";
export {default as profile6} from "./profile-6.png";
export {default as hero_image} from "./hero-image.png";
export {default as about_image} from "./about-image.jpeg";
export {default as building_1} from "./building-1.jpeg";
export {default as building_2} from "./building-2.jpeg";
export {default as building_3} from "./building-3.jpeg";
export {default as building_4} from "./building-4.jpeg";
export {default as building_5} from "./building-5.jpeg";
export {default as building_6} from "./building-6.jpeg";
export {default as building_7} from "./building-7.jpeg";
export {default as building_8} from "./building-8.jpeg";
export {default as building_9} from "./building-9.jpeg";
export {default as building_10} from "./building-10.jpeg";
export {default as blog_1} from "./blog-1.jpeg";
export {default as blog_2} from "./blog-2.jpeg";
export {default as blog_3} from "./blog-3.jpeg";
export {default as home_image1} from "./mitsab-work3.jpeg";
export {default as welder_Work} from "./my-images2.jpeg";
export {default as logo} from "./logo.jpeg";
export {default as home_image2} from "./mitsab-work.png";
export {default as home_image3} from "./pixel1.jpg";
export {default as home_image4} from "./pixel2.jpg";
export {default as home_image5} from "./pixel5.jpg";
export {default as home_image6} from "./pixel4.jpg";
export {default as borehole_image} from "./mitsab_borehole.png";
export {default as borehole_image2} from "./mitsab_borehole2.png";
export {default as mitsab_maintenance} from "./mitsab_maintenance.png";
export {default as tank_maintenance} from "./tank_maintenance.png";
export {default as storage_tank_base} from "./storage_tank_base.jpeg";
export {default as storage_tank_base1} from "./storage_tank_base1.jpeg";
export {default as Renovation_hospital} from "./Renovation_hospital.jpeg";
export {default as Renovation_hospital1} from "./Renovation_hospital1.jpeg";
export {default as infras} from "./infras.png";
export {default as infras2} from "./infras2.png";
export {default as soak_away_pit} from "./soak_away_pit.jpeg";
export {default as soak_away_pit1} from "./soak_away_pit1.jpeg";
export {default as soak_away_pit2} from "./soak_away_pit2.jpeg";
export {default as cat} from "./cat.jpeg";
export {default as cat1} from "./cat1.jpeg";
export {default as cat2} from "./cat2.jpeg";
export {default as cat_video} from "./cat_video.mp4";
export {default as cat4} from "./cat4.jpeg";
export {default as building_res} from "./building_res.png";
export {default as building_res1} from "./building_res1.png";
export {default as portacabin} from "./portacabin.jpeg";
export {default as portacabin1} from "./portacabin1.jpeg";
export {default as portacabin2} from "./portacabin2.jpeg";
export {default as portacabin3} from "./portacabin3.jpeg";
export {default as portacabin4} from "./portacabin4.jpeg";
export {default as Rd_const} from "./Rd_const.jpeg";
export {default as alscon_logo} from "./alscon_logo.jpeg";
export {default as oando_logo} from "./oando_logo.jpeg";
export {default as frontier_logo} from "./frontier_logo.jpeg";
export {default as nepn_logo} from "./nepn_logo.jpeg";
export {default as rusal_logo} from "./rusal_logo.jpeg";
export {default as bp_marine_logo} from "./bp_marine_logo.jpeg";
export {default as mgt} from "./mgt.jpeg";
export {default as mgt1} from "./mgt1.jpeg";
export {default as mgt2} from "./mgt2.png";
export {default as welding} from "./welding.jpeg";
export {default as welding1} from "./welding1.jpeg";
export {default as welding2} from "./welding2.jpeg";
export {default as welding3} from "./welding3.jpeg";
export {default as welding4} from "./welding4.jpeg";
export {default as welding5} from "./welding5.jpeg";
export {default as welding6} from "./welding6.jpeg";


